services:
  app:
    platform: linux/arm64  # Specify the platform
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VUE_APP_HUB_URL=${VUE_APP_HUB_URL}
      - VUE_APP_HUB_IP=${VUE_APP_HUB_IP}
      - VUE_APP_HUB_PORT=${VUE_APP_HUB_PORT}
      - VUE_APP_HUB_API_KEY=${VUE_APP_HUB_API_KEY}
      - VUE_APP_CAMERA_NAME_WHITELIST_REGEX=${VUE_APP_CAMERA_NAME_WHITELIST_REGEX}
    env_file:
      - .env
