services:
  app:
    platform: linux/arm64  # Specify the platform
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VUE_APP_HUB_IP=${HUB_IP}
      - VUE_APP_HUB_PORT=${HUB_PORT}
      - VUE_APP_HUB_API_KEY=${HUB_API_KEY}
      - VUE_APP_CAMERA_NAME_WHITELIST_REGEX=${CAMERA_NAME_WHITELIST_REGEX}
    env_file:
      - .env
